# Generated by Django 3.2.4 on 2021-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210620_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
